{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "Created on Mon Mar 22 09:18:51 2021\n",
    "https://stackoverflow.com/questions/15721094/detecting-mouse-event-in-an-image-with-matplotlib\n",
    "@author: dhelman-lab {new 1 - change the text}\n",
    "\n",
    "=================================================================================\n",
    "========== This code contains a change in the header of the plotted data ========\n",
    "=================================================================================\n",
    "\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "\n",
    "fig, ax = plt.subplots(2,2)\n",
    "\n",
    "ax[0,1].grid(False)\n",
    "ax[0,1].set_xticks([])\n",
    "ax[0,1].set_yticks([])\n",
    "ax[1,1].remove()\n",
    "\n",
    "gs      = gridspec.GridSpec(2,2)\n",
    "ax[1,0] = plt.subplot(gs[1,:])\n",
    "textbox = 'Channels and values:'\n",
    "ax[0,1].text(0.0,1.0,textbox, fontsize=10, verticalalignment='top')\n",
    "\n",
    "im = band\n",
    "x  = np.array([0, 1, 2, 3 ])\n",
    "y  = np.array([3, 8, 1, 10])\n",
    "\n",
    "implot = ax[0,0].imshow(im)\n",
    "\n",
    "ax[1,0].plot([0,0,0], [0,0,0])\n",
    "\n",
    "def onclick(event):\n",
    "   if event.xdata != None and event.ydata != None:\n",
    "       x = event.xdata\n",
    "       y = event.ydata\n",
    "       # We need to select a single layer (channel) from the 3-D array: \n",
    "       t = sub_data[:,int(y),int(x)]\n",
    "       round = np.around(t, 11) \n",
    "\n",
    "       # text =============================================================== #\n",
    "       # Clear axis\n",
    "       ax[0,1].clear()\n",
    "       ax[0,1].grid(False)\n",
    "       ax[0,1].set_xticks([])\n",
    "       ax[0,1].set_yticks([])\n",
    "\n",
    "       # Write new text\n",
    "       textbox = 'Wavelength [\\u00b5m]      Irr [mW m$^{-2}$ (cm$^{-1}$)$^{-1}$]'  + \\\n",
    "        '  \\n' + '----------------------------------------------------------'  + \\\n",
    "        '  \\n' + '         0.6                         ' + str(round[0]) + \\\n",
    "        '  \\n' + '         0.8                         ' + str(round[1]) + \\\n",
    "        '  \\n' + '         1.6                         ' + str(round[2]) + \\\n",
    "        '  \\n' + '         3.9                         ' + str(round[3]) + \\\n",
    "        '  \\n' + '         6.2                         ' + str(round[4]) + \\\n",
    "        '  \\n' + '         7.3                         ' + str(round[5]) + \\\n",
    "        '  \\n' + '         8.7                         ' + str(round[6]) + \\\n",
    "        '  \\n' + '         9.7                         ' + str(round[7]) + \\\n",
    "        '  \\n' + '         10.8                       '  + str(round[8]) + \\\n",
    "        '  \\n' + '         12.0                       '  + str(round[9]) + \\\n",
    "        '  \\n' + '         13.4                       '  + str(round[10])\n",
    "\n",
    "       ax[0,1].text(0.04,0.95,textbox, fontsize=10, verticalalignment='top')\n",
    "\n",
    "       # ==================================================================== #\n",
    "       # Lines ============================================================== #\n",
    "       # Lines remove\n",
    "\n",
    "       ax[1,0].lines.remove(ax[1,0].lines[0])\n",
    "    \n",
    "       # Draw new lines\n",
    "       ax[1,0].plot([0.6,0.8,1.6,3.9,6.2,7.3,8.7,9.7,10.8,12,13.4], t, color='black', marker='o', linestyle='dashed')\n",
    "       ax[1,0].set_xlabel('Wavelength [\\u00b5m]')\n",
    "       ax[1,0].set_ylabel('Irradiance [mW m$^{-2}$ (cm$^{-1}$)$^{-1}$]') # mW m-2 sr-1 (cm-1)-1\n",
    "\n",
    "       # ==================================================================== #\n",
    "\n",
    "       plt.draw()\n",
    "\n",
    "cid = fig.canvas.mpl_connect('button_press_event', onclick)\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
