{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "Created on Mon Mar 22 09:18:51 2021\n",
    "https://stackoverflow.com/questions/15721094/detecting-mouse-event-in-an-image-with-matplotlib\n",
    "@author: dhelman-lab {new 2 - change display color to grey}\n",
    "\n",
    "=================================================================================\n",
    "========== This code displays the TB of the channels                     ========\n",
    "=================================================================================\n",
    "1) displays Tb image in day natural color\n",
    "2) remove the first 3 bands from the graph\n",
    "\n",
    "\"\"\"\n",
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.gridspec as gridspec\n",
    "from astropy.visualization import make_lupton_rgb\n",
    "\n",
    "fig, ax = plt.subplots(2,2)\n",
    "\n",
    "ax[0,1].grid(False)\n",
    "ax[0,1].set_xticks([])\n",
    "ax[0,1].set_yticks([])\n",
    "ax[1,1].remove()\n",
    "\n",
    "gs      = gridspec.GridSpec(2,2)\n",
    "ax[1,0] = plt.subplot(gs[1,:])\n",
    "textbox = 'Channels and values:'\n",
    "ax[0,1].text(0.0,1.0,textbox, fontsize=10, verticalalignment='top')\n",
    "\n",
    "r1 = sub_data[2]\n",
    "g1 = sub_data[1]\n",
    "b1 = sub_data[0]\n",
    "\n",
    "im = make_lupton_rgb(r1, g1, b1)\n",
    "\n",
    "implot = ax[0,0].imshow(im, cmap='Greys_r')\n",
    "\n",
    "ax[1,0].plot([0,0,0], [0,0,0])\n",
    "\n",
    "def onclick(event):\n",
    "   if event.xdata != None and event.ydata != None:\n",
    "       x = event.xdata\n",
    "       y = event.ydata\n",
    "       # We need to select a single layer (channel) from the 3-D array: \n",
    "       t = T_rad[3:11,int(y),int(x)]\n",
    "       round = np.around(t, 8) \n",
    "\n",
    "       # text =============================================================== #\n",
    "       # Clear axis\n",
    "       ax[0,1].clear()\n",
    "       ax[0,1].grid(False)\n",
    "       ax[0,1].set_xticks([])\n",
    "       ax[0,1].set_yticks([])\n",
    "\n",
    "       # Write new text\n",
    "       textbox = 'Channel      Wavelength [\\u00b5m]      Temp (\\N{DEGREE SIGN}C)'  + \\\n",
    "        '  \\n' + '----------------------------------------------------------'  + \\\n",
    "        '  \\n' + 'CH04                     3.9                   ' + \"{:.2f}\".format(round[0]) + \\\n",
    "        '  \\n' + 'CH05                     6.2                   ' + \"{:.2f}\".format(round[1]) + \\\n",
    "        '  \\n' + 'CH06                     7.3                   ' + \"{:.2f}\".format(round[2]) + \\\n",
    "        '  \\n' + 'CH07                     8.7                   ' + \"{:.2f}\".format(round[3]) + \\\n",
    "        '  \\n' + 'CH08                     9.7                   ' + \"{:.2f}\".format(round[4]) + \\\n",
    "        '  \\n' + 'CH09                     10.8                 '  + \"{:.2f}\".format(round[5]) + \\\n",
    "        '  \\n' + 'CH10                     12.0                 '  + \"{:.2f}\".format(round[6]) + \\\n",
    "        '  \\n' + 'CH11                     13.4                 '  + \"{:.2f}\".format(round[7]) #+ \\\n",
    "        #'  \\n' + '-----------------------------------------------------------' + \\\n",
    "        #'  \\n' + 'SST                      '\n",
    "\n",
    "       ax[0,1].text(0.04,0.95,textbox, fontsize=10, verticalalignment='top')\n",
    "\n",
    "       # ==================================================================== #\n",
    "       # Lines ============================================================== #\n",
    "       # Lines remove\n",
    "\n",
    "       ax[1,0].lines.remove(ax[1,0].lines[0])\n",
    "    \n",
    "       # Draw new lines\n",
    "       ax[1,0].plot([3.9,6.2,7.3,8.7,9.7,10.8,12,13.4], t, color='black', marker='o', linestyle='dashed')\n",
    "       ax[1,0].set_xlabel('Wavelength [\\u00b5m]')\n",
    "       ax[1,0].set_ylabel('Irradiance [mW m$^{-2}$ (cm$^{-1}$)$^{-1}$]') # mW m-2 sr-1 (cm-1)-1\n",
    "\n",
    "       # ==================================================================== #\n",
    "\n",
    "       plt.draw()\n",
    "\n",
    "cid = fig.canvas.mpl_connect('button_press_event', onclick)\n",
    "\n",
    "### ========================================================================================================= ###\n",
    "### ========================================================================================================= ###\n",
    "### Atmospheric correction for SST ###\n",
    "### 2/3 = k10.8 / (k12 - k10.8)    ###\n",
    "### ========================================================================================================= ###\n",
    "### ========================================================================================================= ###"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
